2538 add import from git workflow using webview UI
redhat-developer/vscode-openshift-tools pull request #2567
Opened 2022-10-13 17:09 UTC by msivasubramaniaan

Signed-off-by: msivasubramaniaan [msivasub@redhat.com](mailto:msivasub@redhat.com)

2022-10-13 17:35 UTC, mohitsuman commented on package.json
> +					"light": "images/title/light/workspace-new.svg",
Add git icon to reflect import from git command.

2022-10-13 17:42 UTC, mohitsuman commented
1. Add a Button `Import from Git` in the Application Explorer section. This will directly open the webview.
2. Once the gitrepo is validated and we change the gitrepo (provide a different URL), the Application name and name text box is not updated.

@msivasubramaniaan ^^

2022-10-14 12:47 UTC, mohitsuman commented on src/webview/git-import/app/cardItem.tsx
> +                        Project Type: {yamlDoc.metadata.projectType}<br />
Let's make sure the Type is `NodeJS` and NOT `nodejs`.

2022-10-14 12:48 UTC, mohitsuman commented on src/webview/git-import/app/cardItem.tsx
> +                        Language: {yamlDoc.metadata.language}<br />
Similarly here to verify the name as NodeJS.

2022-10-14 12:49 UTC, mohitsuman commented on src/webview/git-import/app/gitImport.tsx
> +                                        <Typography variant='h6' className='highlight'>General</Typography>
We do not need General in the UI. Let's remove it.

2022-10-14 13:47 UTC, mohitsuman commented on src/webview/git-import/app/gitImport.tsx
> +                    <Typography variant='h4' className='highlight'>Import from Git</Typography>
Make the heading as `h6`.

2022-10-14 13:49 UTC, mohitsuman commented on src/webview/git-import/app/gitImport.tsx
> +                                color: 'var(--vscode-settings-textInputForeground)'
Make color as `#fe5142`

2022-10-14 13:54 UTC, mohitsuman commented on src/webview/git-import/app/cardItem.tsx
> +                    <Typography variant='body1'>{yamlDoc.metadata.name}</Typography>
Here also we need to keep it full name. Let's see if we can map `metadata.name` to use fullName.

2022-10-14 13:57 UTC, mohitsuman requested changes
Let's get these changes done.

2022-10-14 14:02 UTC, mohitsuman commented on src/webview/git-import/app/gitImport.tsx
> +                                    Cancel
let's have the Cancel Button as Outlined parameter as we have in MUI.

2022-10-22 00:32 UTC, mohitsuman commented
The Cancel button does not work in Light Theme.

<img width="368" alt="Screenshot 2022-10-22 at 5 00 53 AM" src="https://user-images.githubusercontent.com/3133356/197308268-3fc25ced-7f26-45ac-aca4-077100f588a0.png">

2022-10-22 00:58 UTC, mohitsuman approved these changes

2022-10-22 02:49 UTC, gorkem requested changes
This use case needs to be discussed further

2022-10-26 19:49 UTC, mohitsuman commented
@gorkem As discussed, can you please approve the PR and we merge it to main.

2022-10-27 12:58 UTC, mohitsuman approved these changes
LGTM

2022-10-27 13:26 UTC, gorkem requested changes
rename `src/git` to `src/git-import`

Most of the `/utils` package is about detecting projects. Can we use Alizer instead of reimplementing?

2022-10-31 20:51 UTC, dgolovin commented
I get rate limit error right away on first try.
![image](https://user-images.githubusercontent.com/620330/199107976-505c10c7-a00d-4e33-b582-aa70be2fec50.png)

2022-10-31 21:00 UTC, dgolovin commented on src/git/services/git-service.ts
> +export enum SecretType {
Renamed enum so there is not shadowing, but VSCode still complains
![image](https://user-images.githubusercontent.com/620330/199109537-a3047007-1e90-4e8f-a2c0-ea21403f8dea.png)

2022-10-31 21:00 UTC, dgolovin commented
@gorkem renamed git to git-import

2022-10-31 21:10 UTC, mohitsuman commented
> rename `src/git` to `src/git-import`
> 
> Most of the `/utils` package is about detecting projects. Can we use Alizer instead of reimplementing?

For the next iteration, we would be looking to implement with alizer. As alizer only works with local workspace and not remote URL, we need to fix it on alizer and then support it on the extension side. I will keep an issue for the next release. For the 1.0 release, we should be good to implement the current project detection strategy.

2022-11-02 19:30 UTC, mohitsuman approved these changes

2022-11-03 04:36 UTC, dgolovin approved these changes

2022-11-03 04:49 UTC, merged