added switch and delete icons on manage contexts show-pick
redhat-developer/vscode-openshift-tools pull request #2625
Opened 2022-11-04 05:58 UTC by msivasubramaniaan

Signed-off-by: msivasubramaniaan <msivasub@redhat.com>

**Ref:**
![image](https://user-images.githubusercontent.com/93245779/199901283-642a2ffa-26bb-41cc-953d-0a31e6c68e42.png)

2022-11-04 18:23 UTC, mohitsuman submitted a review, later dismissed

2022-11-19 04:56 UTC, dgolovin requested changes
The same issues explained in  review for https://github.com/redhat-developer/vscode-openshift-tools/pull/2678 should be addressed the same way.

2022-11-19 04:56 UTC, dgolovin commented on package.json
> +				"title": "Manage Contexts",
The primary purpose of this feature to switch contexts, so it should be clear what it is and IMO old name should stay.

2022-11-29 06:00 UTC, dgolovin requested changes

2022-11-29 06:00 UTC, dgolovin commented on src/openshift/cluster.ts
> +                        await Cluster.odo.execute(Command.setOpenshiftContext(choice.label));
add `quickPick.hide();` before command execution to hide quickPickInput, because if won't hide by itself in this case.

2022-11-29 06:00 UTC, dgolovin commented on src/openshift/cluster.ts
> +                        await window.showInformationMessage('Are you sure you want to delete this cluster information from kubeconfig?', 'Yes', 'No')
should assign awaited value

`const answer = await ...`

then you do not need to use `then` callback and code would look much cleaner

2022-11-29 06:00 UTC, dgolovin commented on src/openshift/cluster.ts
> +                    if (event.button === deleteBtn) {
this `if` is not needed, because there is only one ItemButton.

2022-11-29 06:00 UTC, dgolovin commented on src/openshift/cluster.ts
> +                    if (selection && selection.length > 0) {
Not needed if selection default value is empty array.

2022-11-29 06:00 UTC, dgolovin commented on src/openshift/cluster.ts
> +                        const choice = Array.from(selection).pop();
this could be just `const choice = selection[0]`.

2022-11-29 22:14 UTC, dgolovin commented
Squashed and pushed here ahttps://github.com/redhat-developer/vscode-openshift-tools/pull/2684.

2022-11-29 22:14 UTC, closed without merging