1802 provide a way to remove clusters from the list
redhat-developer/vscode-openshift-tools pull request #2678
Opened 2022-11-18 12:16 UTC by msivasubramaniaan

Signed-off-by: msivasubramaniaan [msivasub@redhat.com](mailto:msivasub@redhat.com)

This will fix https://github.com/redhat-developer/vscode-openshift-tools/issues/1802

**Post Fix:**
![delete-cluster-demo](https://user-images.githubusercontent.com/93245779/202703027-9e031375-c1e3-43e8-8fd1-984b5541f8be.gif)

2022-11-18 12:26 UTC, mohitsuman commented
@msivasubramaniaan what exactly changed between commit [ad6dda7](https://github.com/redhat-developer/vscode-openshift-tools/pull/2678/commits/ad6dda752ae809172f39b3313b6dafd474eab6f1) & [9945c2a](https://github.com/redhat-developer/vscode-openshift-tools/pull/2678/commits/9945c2aa0739f17ff9dcfc41e2f818f730c0fbdc) .

2022-11-18 12:28 UTC, msivasubramaniaan commented
> @msivasubramaniaan what exactly changed between commit [ad6dda7](https://github.com/redhat-developer/vscode-openshift-tools/pull/2678/commits/ad6dda752ae809172f39b3313b6dafd474eab6f1) & [9945c2a](https://github.com/redhat-developer/vscode-openshift-tools/pull/2678/commits/9945c2aa0739f17ff9dcfc41e2f818f730c0fbdc) .

wrongly committed the .editorConfig file, so reverted and add the particular files

2022-11-19 04:48 UTC, dgolovin requested changes
There should be no item buttons for **Provide new URL...** item and switch item button for every server url. You ser should be selecting items from quick pick list as usual. There **onDidAccept** listener for that.

2022-11-19 04:48 UTC, dgolovin commented on src/openshift/cluster.ts
> +                if (event.button instanceof quickBtn) {
This instanceof check is not required.

2022-11-19 04:48 UTC, dgolovin commented on src/openshift/cluster.ts
> +            const contextNames: QuickPickItem[] = clusterItems.map((ctx) => ({ label: `${ctx.label}`, buttons: [switchBtn, deleteBtn] }));
No need to have **switchBtn**, just recognize selection of cluster in **onDidAccept** listener.

2022-11-19 04:48 UTC, dgolovin commented on src/openshift/cluster.ts
> +            const createUrl: QuickPickItem = { label: 'Provide new URL...', buttons: [addBtn] };
**addBtn** is not needed, just recognize Add quickpick in **onDidAccept** listener.

2022-11-19 04:48 UTC, dgolovin commented on src/openshift/cluster.ts
> +                    if (event.button.iconPath.id === 'plus') {
Recognize **Provide New URL...** item in **onDidAccept** listener and move code from this if there.

2022-11-19 04:48 UTC, dgolovin commented on src/openshift/cluster.ts
> +                    } else if (event.button.iconPath.id === 'arrow-swap') {
move this code in **onDidAccept** listener

2022-11-19 04:48 UTC, dgolovin commented on src/openshift/cluster.ts
> +                    } else if (event.button.iconPath.id === 'trash') {
Use direct comparison **event.button === deleteBtn**.

2022-11-19 04:48 UTC, dgolovin commented on src/openshift/cluster.ts
> +                                        reject(null);
Show error message from the **err** exception.

2022-11-19 04:48 UTC, dgolovin commented on src/openshift/cluster.ts
> +                                        await k8sConfig.deleteCluster(cluster);
use `CliChannel.getInstance().execTool(Command.deleteCluster(cluster.name)`

2022-11-19 04:48 UTC, dgolovin commented on src/util/kubeUtils.ts
> +import { OdoImpl } from '../odo';
No changes required in this file if **CliChannel** class is used (see above).

2022-11-22 05:29 UTC, dgolovin requested changes
Couple more changes and it should be good to go.

2022-11-29 04:56 UTC, dgolovin requested changes
`Houston we have a problem!`

After deleting the CRC cluster with

```
"/home/denis/p/vscode-openshift-tools/out/tools/linux/oc" config delete-cluster api-crc-testing:6443
deleted cluster api-crc-testing:6443 from /home/denis/.kube/config
```

two contexts left in config file:
* crc-developer
* crc-admin

both can be selected in Switch context command and that leads to Application Explorer view showing welcome page with buttons. This is not correct because user is not logged out of cluster or cluster is not accessible. It is because the config is broken and any command that need config fails with error like this:

```
"/home/denis/p/vscode-openshift-tools/out/tools/linux/oc" get project -o=json

error: Missing or incomplete configuration info.  Please point to an existing, complete config file:

  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
```

That leads to more problems after CRC restart:

```
INFO Operators are stable (3/3)...                
INFO Adding crc-admin and crc-developer contexts to kubeconfig... 
ERRO Cannot update kubeconfig: Head "https://oauth-openshift.apps-crc.testing": dial tcp 192.168.130.11:443: connect: connection refused 
Started the OpenShift cluster.
```

Which lead to CRC not being able to add CRC related objects to config because it is broken.

Considering all this we should ether use k8s javascript client to traverse the config structure and firs remove all related contexts, then all related users, finally cluster itself, or execute several commands 'oc  config delete-context/delete-user/delete-cluster'.

I am leaning to use oc command so we don't have to deal with configuration loaded from several config files configured in KUBECONFIG evn variable.

2022-11-30 17:30 UTC, msivasubramaniaan commented
> `Houston we have a problem!`
> 
> After deleting the CRC cluster with
> 
> ```
> "/home/denis/p/vscode-openshift-tools/out/tools/linux/oc" config delete-cluster api-crc-testing:6443
> deleted cluster api-crc-testing:6443 from /home/denis/.kube/config
> ```
> 
> two contexts left in config file:
> 
> * crc-developer
> * crc-admin
> 
> both can be selected in Switch context command and that leads to Application Explorer view showing welcome page with buttons. This is not correct because user is not logged out of cluster or cluster is not accessible. It is because the config is broken and any command that need config fails with error like this:
> 
> ```
> "/home/denis/p/vscode-openshift-tools/out/tools/linux/oc" get project -o=json
> 
> error: Missing or incomplete configuration info.  Please point to an existing, complete config file:
> 
>   1. Via the command-line flag --kubeconfig
>   2. Via the KUBECONFIG environment variable
>   3. In your home directory as ~/.kube/config
> 
> To view or setup config directly use the 'config' command.
> ```
> 
> That leads to more problems after CRC restart:
> 
> ```
> INFO Operators are stable (3/3)...                
> INFO Adding crc-admin and crc-developer contexts to kubeconfig... 
> ERRO Cannot update kubeconfig: Head "https://oauth-openshift.apps-crc.testing": dial tcp 192.168.130.11:443: connect: connection refused 
> Started the OpenShift cluster.
> ```
> 
> Which lead to CRC not being able to add CRC related objects to config because it is broken.
> 
> Considering all this we should ether use k8s javascript client to traverse the config structure and firs remove all related contexts, then all related users, finally cluster itself, or execute several commands 'oc config delete-context/delete-user/delete-cluster'.
> 
> I am leaning to use oc command so we don't have to deal with configuration loaded from several config files configured in KUBECONFIG evn variable.

@dgolovin as per your comment, currently I am deleting the context, user and finally the cluster

2022-12-01 06:09 UTC, dgolovin approved these changes
Updated code and created commit per change with description what was done.

2022-12-01 06:09 UTC, merged