upstream material-ui to v5
redhat-developer/vscode-openshift-tools pull request #2691
Opened 2022-12-02 07:10 UTC by msivasubramaniaan

Signed-off-by: msivasubramaniaan <msivasub@redhat.com>

Fix: https://github.com/redhat-developer/vscode-openshift-tools/issues/2689

2022-12-02 13:45 UTC, mohitsuman requested changes

2022-12-02 13:45 UTC, mohitsuman commented on package.json
> -		"@material-ui/core": "^4.12.3",
@msivasubramaniaan As we have removed this, should the reference of this in files be also updated such as here: https://github.com/redhat-developer/vscode-openshift-tools/blob/main/src/webview/cluster/app/cluster.style.tsx#L6

We need to be update all the location where the references are added for old dependency.

2022-12-13 11:36 UTC, msivasubramaniaan commented
@mohitsuman as the reference of createStyles from v4 to v5 internally taken care through @mui/systems. Now the build has success

2022-12-16 06:10 UTC, mohitsuman requested changes

2022-12-16 06:10 UTC, mohitsuman commented on package.json
> +		"@mui/material": "^5.10.16",
Let's keep it to the latest version 5.11.0

2022-12-16 06:10 UTC, mohitsuman commented on package.json
>  		"@mui/lab": "^5.0.0-alpha.61",
We should also update the @mui/lab version to latest 5.0.0-alpha.112

2022-12-16 06:10 UTC, mohitsuman commented on package.json
>  		"@mui/icons-material": "^5.2.5",
Similarly with the icons-material to latest.

2022-12-16 06:10 UTC, mohitsuman commented on package.json
>  		"@patternfly/react-core": "^4.198.19",
@msivasubramaniaan are we using anything patternfly in our codebase ?

2022-12-16 06:10 UTC, mohitsuman commented on package.json
>  		"@rjsf/material-ui": "^3.2.1",
Similarly are we using this module anywhere ? As this material UI still point to v4 and we have to move to v5. So need to check if this is needed.

2022-12-16 15:03 UTC, mohitsuman approved these changes

2022-12-16 15:41 UTC, merged