Add survey webview
redhat-developer/vscode-openshift-tools pull request #2925
Opened 2023-06-01 06:24 UTC by msivasubramaniaan

2023-06-01 18:05 UTC, datho7561 requested changes

2023-06-01 18:05 UTC, datho7561 commented on src/webview/feedback/feedbackLoader.ts
> +    // eslint-disable-next-line @typescript-eslint/explicit-function-return-type
Give the function a return type instead of ignoring the linting issue

2023-06-04 21:37 UTC, mohitsuman commented
- OpenShift Logo is distorted. Need to align it properly. See screenshot.

<img width="414" alt="Screenshot 2023-06-05 at 3 06 02 AM" src="https://github.com/redhat-developer/vscode-openshift-tools/assets/3133356/f2fb11e2-b3f1-40ce-9390-b09898661f51">

2023-06-04 21:38 UTC, mohitsuman commented on src/webview/feedback/app/feedback.tsx
> +                        <Typography variant='caption' style={{ marginTop: '2px' }} className='foreGroundColor'>Your opinion matters to us!</Typography>
`Your opinion matters to us!` should be written beside the OpenShift logo and in a bigger font size.

2023-06-04 21:40 UTC, mohitsuman commented on src/webview/feedback/app/feedback.tsx
> +            <Survey model={feedbackModal} />
@msivasubramaniaan The font size of the questions are very small. Let's increase the size of the Qs.

2023-06-04 21:42 UTC, mohitsuman commented on src/webview/feedback/app/feedback.tsx
> +                        <a href='https://github.com/redhat-developer/vscode-openshift-tools'>
Use this URL https://github.com/redhat-developer/vscode-openshift-tools/issues

2023-06-04 21:58 UTC, mohitsuman commented on src/webview/feedback/json.js
> +                    'rateDisplayMode': 'smileys',
Let's use numbers 1-5 to rate. As the smiley with heart eyes can only be used for 2-10 rating. For 1-5 rating, it does not represent the correct smileys as expected.

2023-06-04 21:58 UTC, mohitsuman commented on src/webview/feedback/json.js
> +                    'rateDisplayMode': 'smileys',
Similar change with rating based on numbers 1-5.

2023-06-04 22:00 UTC, mohitsuman commented on src/webview/feedback/json.js
> +                    'placeholder': 'Please specify the similar extension...'
```suggestion
                    'placeholder': 'Please mention the similar extension name/URL.'
```

2023-06-04 22:04 UTC, mohitsuman commented on src/webview/feedback/json.js
> +                    'title': 'Have you used similar extension before?'
```suggestion
                    'title': 'Please mention any other similar extension you use together with OpenShift Toolkit?'
```

2023-06-04 22:13 UTC, mohitsuman commented on src/webview/feedback/json.js
> +                    'title': 'What, if anything, do you find frustrating or unappealing about the extension ?'
```suggestion
                    'title': 'What, if anything, do you find frustrating or challenging about the extension workflow?
```

2023-06-04 22:29 UTC, mohitsuman commented on src/webview/feedback/json.js
> +                    'placeholder': 'Enter email address, phone number or leave blank for anonymous feedback'
```suggestion
                    'placeholder': 'Provide email address or leave blank for anonymous feedback'
```

2023-06-04 22:31 UTC, mohitsuman requested changes
Some wording changes

2023-06-06 15:55 UTC, mohitsuman commented on src/webview/feedback/app/feedback.tsx
> +                                    <Typography variant='body2' className='footerText'>Rate us on Marketplace</Typography>
The animation of underlining does not happen in the text. It happens on the MSFT logo. it works well for the GitHub icon and text.

2023-06-06 15:55 UTC, mohitsuman commented on src/webview/feedback/app/feedback.tsx
> +                <Typography variant='subtitle2' className='foreGroundColor'>This survey will take about 3 minutes. Your feedback is extremely valuable and will directly impact the product moving forw
```suggestion
                <Typography variant='subtitle2' className='foreGroundColor'>This survey will take about 2 minutes. Your feedback is extremely valuable and will directly impact the product moving forward.</Typography>
```

2023-06-06 15:56 UTC, mohitsuman commented on src/webview/feedback/app/index.html
> +        <title>Feedback</title>
```suggestion
        <title>Share Feedback</title>
```

2023-06-06 15:57 UTC, mohitsuman requested changes
Few changes.

2023-06-06 17:10 UTC, mohitsuman commented on src/webview/feedback/app/index.html
> +        <title>Feedback</title>
@msivasubramaniaan is this done ?

2023-06-06 17:12 UTC, msivasubramaniaan commented on src/webview/feedback/app/index.html
> +        <title>Feedback</title>
yes

2023-06-06 17:23 UTC, mohitsuman approved these changes
LGTM

2023-06-06 17:57 UTC, datho7561 approved these changes
Looks good! Thanks Muthu!

2023-06-06 18:03 UTC, merged