Contribute cloud explorer
redhat-developer/vscode-openshift-tools pull request #2962
Opened 2023-06-12 15:07 UTC by JessicaJHee

Closes https://github.com/redhat-developer/vscode-openshift-tools/pull/2620

2023-06-13 09:56 UTC, mohitsuman commented on package.json
> +				"title": "Open Console",
```suggestion
				"title": "Open Developer Console",
```

2023-06-13 09:57 UTC, mohitsuman commented on package.json
> +				"title": "Signup for Sandbox",
```suggestion
				"title": "Provision OpenShift Developer Sandbox",
```

2023-06-13 09:59 UTC, mohitsuman requested changes
wording changes.

2023-06-19 09:21 UTC, msivasubramaniaan approved these changes
LGTM

Tested in my local and it works as expected

2023-06-19 17:47 UTC, mohitsuman commented
@JessicaJHee Let's add tooltip for Developer Sandbox and OpenShift Local.

2023-06-19 18:05 UTC, JessicaJHee commented
> @JessicaJHee Let's add tooltip for Developer Sandbox and OpenShift Local.

Here's what it looks like now:
![Peek 2023-06-19 14-04](https://github.com/redhat-developer/vscode-openshift-tools/assets/73968480/d351ae48-e10b-4a8f-a18b-4500faa58f69)

2023-06-19 18:40 UTC, mohitsuman commented on src/cloudProvider/redhatCloudProvider.ts
> +        openshiftLocalItem.iconPath = new vscode.ThemeIcon('symbol-folder');
@JessicaJHee We should use the `vm` icon here for OpenShift local.

2023-06-19 18:40 UTC, mohitsuman commented on src/cloudProvider/redhatCloudProvider.ts
> +        sandboxItem.iconPath = new vscode.ThemeIcon('vm');
@JessicaJHee We should use the `openshift logo` icon here instead of vm one.

2023-06-19 18:41 UTC, mohitsuman reviewed
Change the icons for the cluster providers.

2023-06-19 19:19 UTC, mohitsuman approved these changes
lgtm

2023-06-19 20:21 UTC, merged