3010 create UI for serverless invoke function
redhat-developer/vscode-openshift-tools pull request #3115
Opened 2023-08-21 18:07 UTC by msivasubramaniaan

Fixes: https://github.com/redhat-developer/vscode-openshift-tools/issues/3010

2023-08-21 20:47 UTC, datho7561 commented
Seems pretty good so far! A few quick comments, I'll take a look at the code as well.
- Displaying the result as a popup message isn't that helpful, since the content gets cut off if its long. Also, the message is hidden within a few seconds. I think it would be nice to put the result in a new text editor, similar to what "Load" does for Deployments.
- In the case that the function invocation fails, for example when the function isn't running, there is no error message
- In the case of `crc`, we cannot invoke the function, since the certificate isn't trusted, since it's self-signed. It would be nice to configure the certificate so that it's trusted, or at least show an error message as to why it fails

2023-08-23 08:46 UTC, msivasubramaniaan commented
> Seems pretty good so far! A few quick comments, I'll take a look at the code as well.
> 
> * Displaying the result as a popup message isn't that helpful, since the content gets cut off if its long. Also, the message is hidden within a few seconds. I think it would be nice to put the result in a new text editor, similar to what "Load" does for Deployments.
> * In the case that the function invocation fails, for example when the function isn't running, there is no error message
> * In the case of `crc`, we cannot invoke the function, since the certificate isn't trusted, since it's self-signed. It would be nice to configure the certificate so that it's trusted, or at least show an error message as to why it fails

Addressed the mentioned comments. Please have a look

2023-08-23 16:26 UTC, datho7561 requested changes
The invoke functionality seems to be working. Here are a few things I found in the code.

2023-08-23 16:26 UTC, datho7561 commented on src/serverlessFunction/functionImpl.ts
> +    getFunctionStatus(funcData: FunctionContent, deployedFunctions: FunctionObject[]): [FunctionStatus, string] {
Add the URL as an optional field of `FunctionStatus` instead of a separate return item

2023-08-23 16:26 UTC, datho7561 commented on src/webview/serverless-function/app/home.tsx
> +                    </Container>
Move the code surrounding the invoke component and the create function component into their respective components. eg.:

```tsx
this.state.invoke ?
<InvokeFunction />
: <CreateFunction />
```

Then put the title and container into the `InvokeFunction` and `CreateFunction`

2023-08-24 14:37 UTC, datho7561 requested changes
Two more quick comments

2023-08-24 14:37 UTC, datho7561 commented on package.json
> +		"uuid": "^9.0.0",
There is a built-in library for this in NodeJS: https://nodejs.org/docs/latest-v16.x/api/crypto.html#cryptorandomuuidoptions.

2023-08-24 14:37 UTC, datho7561 commented on src/serverlessFunction/functionImpl.ts
> +    getCommanFunction(funcData: FunctionContent, deployedFunctions: FunctionObject[]): DeployedFunction {
getDeployedFunction

2023-08-25 13:08 UTC, datho7561 approved these changes
Looks good. Thanks, Muthu!

2023-08-25 13:09 UTC, datho7561 commented
There are merge conflicts, I can't merge yet

2023-08-25 14:06 UTC, merged