add port number support
redhat-developer/vscode-openshift-tools pull request #3292
Opened 2023-09-20 07:08 UTC by msivasubramaniaan

Fixes: https://github.com/redhat-developer/vscode-openshift-tools/issues/2781

2023-09-20 14:57 UTC, datho7561 requested changes

2023-09-20 14:57 UTC, datho7561 commented on src/webview/common/componentNameInput.tsx
> +                }} />
This component is for the component name input field. Please do one of the following:
- Move the code for the port input field into its own component
- Rename the component to reflect that it also contains the port input field

2023-09-20 14:57 UTC, datho7561 commented on src/webview/common-ext/createComponentHelpers.ts
> +        validationMessage = NameValidator.lengthName(
If I want to set the port to `20`, then I have to enter `00020`. Is it possible to validate the port based only on the value of the number?

2023-09-20 18:02 UTC, msivasubramaniaan commented
@datho7561 Thanks for your review. I just addressed the review comments and pushed the code. Can you please have a look on the latest code?

2023-09-20 19:41 UTC, datho7561 approved these changes
Looks good, and works well. Thanks, Muthu!

2023-09-20 19:42 UTC, datho7561 commented
It seems like there are linter errors

2023-09-21 06:27 UTC, msivasubramaniaan commented
> It seems like there are linter errors

Fixed lint errors

2023-09-21 09:33 UTC, mohitsuman commented
@msivasubramaniaan can you please share the gif/video of how it behaves.

2023-09-21 12:54 UTC, datho7561 commented
Here's what it looks like:

![Screenshot from 2023-09-21 08-53-28](https://github.com/redhat-developer/vscode-openshift-tools/assets/22376627/21352701-78c9-441a-94c8-634c21dd515b)

2023-09-21 13:25 UTC, datho7561 commented
The integration tests seem to be failing.

2023-09-22 14:08 UTC, msivasubramaniaan commented
@mohitsuman Here is the demo gif:
![port-number](https://github.com/redhat-developer/vscode-openshift-tools/assets/93245779/e34251b2-4b97-430f-b0e1-1a0dcc97005b)

2023-09-22 14:21 UTC, datho7561 commented
Currently, you can't set the port for components created from template or imported from git

2023-09-22 15:22 UTC, datho7561 approved these changes
Looks good! Feel free to merge after rebasing

2023-09-23 05:25 UTC, merged

2023-09-23 05:25 UTC, msivasubramaniaan commented
@datho7561 Thanks for your review.