Added alizer analyze command
redhat-developer/vscode-openshift-tools pull request #4330
Opened 2024-07-30 17:41 UTC by msivasubramaniaan

Ref: https://github.com/redhat-developer/vscode-openshift-tools/issues/4320

2024-07-30 20:44 UTC, datho7561 commented
I still don't think I get the point of this PR. If we are removing `odo` completely, then we won't be able to work with Devfiles, so we won't need to analyze which one to use.

I understand using alizer instead of odo for https://github.com/redhat-developer/vscode-openshift-tools/pull/4235 , but that's not what this is.

2024-08-01 13:30 UTC, msivasubramaniaan commented
> I still don't think I get the point of this PR. If we are removing `odo` completely, then we won't be able to work with Devfiles, so we won't need to analyze which one to use.
> 
> I understand using alizer instead of odo for #4235 , but that's not what this is.

Hello @datho7561 
As this PR for just replace `odo analyze` command with `alizer devfile`. It is common for both component creation using git import and #4235

2024-08-01 15:13 UTC, datho7561 requested changes
From my manual testing, this seems good. I noticed two small things in the code.

2024-08-01 15:13 UTC, datho7561 commented on src/odo/odoWrapper.ts
> +        return [[...parse].shift()];
Shift returns the first element. Why not just return the first element (or undefined if there is no element) and change the return type to `Promise<AlizerAnalyzeResponse>` ?

2024-08-01 15:13 UTC, datho7561 commented on src/odo/odoWrapper.ts
> +    public async alizerAnalyze(currentFolderPath: Uri): Promise<AlizerAnalyzeResponse[]> {
It might be a good idea to move this function to it's own file, since it no longer uses odo, and this file contains wrappers around odo commands

2024-08-02 14:57 UTC, vrubezhny requested changes
`odoWrapper` test also needs some attention.

2024-08-02 14:57 UTC, vrubezhny commented on test/integration/odoWrapper.test.ts
>          test('analyze()', async function () {
@msivasubramaniaan The `test('analyze()', async function () {` test case should probably also be moved out from `test/integration/odoWrapper.test.ts` into a separate test, shouldn't it?

2024-08-10 21:23 UTC, vrubezhny commented
@msivasubramaniaan The related test are still failing:

```
1) Create component from git URL
2) "after each" hook: context for "Create component from git URL"
3) "after all" hook: context for "Create component from template project"
 ```
 
 The first one looks like hangs or take a vary long time to complete, causing the following tests to fail too. But it could be also that some `alizer` related code failure causes it not to finish successfully.
 
 Could you please take a look?

2024-08-13 11:09 UTC, msivasubramaniaan commented
@datho7561 and @vrubezhny Moved `odo analyze` command and corresponding test cases as well. Please review and merge. Once this merged I will make the https://github.com/redhat-developer/vscode-openshift-tools/pull/4235 PR ready

2024-08-13 18:14 UTC, vrubezhny approved these changes
Looks good to me. Thanks!

2024-08-15 17:04 UTC, datho7561 requested changes

2024-08-16 14:29 UTC, datho7561 approved these changes
Looks good to me. Thanks, Muthu!

2024-08-16 14:30 UTC, merged