removed ODO log command
redhat-developer/vscode-openshift-tools pull request #4566
Opened 2024-10-17 16:19 UTC by msivasubramaniaan

Ref: https://github.com/redhat-developer/vscode-openshift-tools/issues/4396

Removed `Show Log` and `Follow Log` on the dropdown of component. We can use `Watch Logs` on `Deployments` and `Pods` in application explorer view.

2024-10-17 17:06 UTC, vrubezhny requested changes
Once we don't use show&watch logs - shouldn't we remove the commands themselves here: https://github.com/redhat-developer/vscode-openshift-tools/blob/3d7ccfc447cd9501fcb578691e6d365e1a2a649e/src/odo/command.ts#L49-L61 ?

2024-10-17 17:06 UTC, vrubezhny commented on src/openshift/component.ts
> -        const showLogCmd = Command.showLog(Component.getDevPlatform(componentFolder));
Shouldn't we remove the command itself then?

2024-10-17 17:07 UTC, vrubezhny commented on src/openshift/component.ts
> -        const showLogCmd = Command.showLogAndFollow(Component.getDevPlatform(componentFolder));
Same here. Shouldn't we remove the command itself?

2024-10-17 18:07 UTC, msivasubramaniaan commented on package.json
> -		"onCommand:openshift.component.log",
@vrubezhny I removed the command as well

2024-10-17 19:07 UTC, datho7561 approved these changes
Seems good to me. Thanks, Muthu!

2024-10-17 21:26 UTC, vrubezhny commented
@msivasubramaniaan Please take a look at https://github.com/redhat-developer/vscode-openshift-tools/pull/4566#pullrequestreview-2375800902 - I mean, you're removing all the "show/watch log"-like commands from palette/context menu/etc., but you're not removing the code in `odo/command.ts` that contains the methods that provide the implementations for these 'ODO` commands:

```
static showLog(platform?: string): CommandText {...}

static showLogAndFollow(platform?: string): CommandText {...}
```
... which look like aren't used anymore (after your PR is merged).

Do you want to keep these methods for any reason?

2024-10-18 12:15 UTC, lgrossma commented on test/ui/suite/componentContextMenu.ts
Is it necessary to delete these two tests entirely? If `odo log` gets replaced by different solution, these tests could be still used.. ()

2024-10-18 12:56 UTC, msivasubramaniaan commented on test/ui/suite/componentContextMenu.ts
As plan to get rid of ODO, I removed the whole code and these log functionality is working through `oc logs`. But not in the component level. It will be on deployment and pod level.

2024-10-18 13:13 UTC, vrubezhny approved these changes
Look good to me. Thanks!

2024-10-18 13:15 UTC, merged

2024-10-18 13:32 UTC, lgrossma commented on test/ui/suite/componentContextMenu.ts
I still think it is pretty handy to be able to check the logs in component view and not having to look for the right deployment in the deployments view..